### ISSUE TITLE
Exception on startup: com.samczsun.skype4j.exceptions.ConnectionException: While logging in (401 Unauthorized)

### ISSUE THREAD

**Issue by ghost** [last-khajiit/skype2gitter#2]
when i open the .bat file this happens,and i already finished the configuration file
C:\Users\MatthewJP\Downloads\skype2gitter-0.1 (1)>java -jar skype2gitter-0.1.jar
com.samczsun.skype4j.exceptions.ConnectionException: While logging in (401 Unauthorized)
        at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:50)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:372)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:302)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:282)
        at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:69)
        at com.last_khajiit.skype2gitter.SkypeUtils.processSkypeMessages(SkypeUtils.java:31)
        at com.last_khajiit.skype2gitter.Skype2Gitter.main(Skype2Gitter.java:33)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by hleb-kastseika** [comment]
Possibly, it's related to [Skype4J issue](https://github.com/samczsun/Skype4J/issues/105), I'm investigating it further

**Comment by hleb-kastseika** [comment]
@mjpitsicalis2 I tried to reproduce the issue with email as Skype login and also got similar exception. It's really related to mentioned issue with Skype4J. 

I see, the bug was reported at July 2016 and last activity was there at October 2016 (last commit to project almost year ago). It seems to me, as long-term solution we need to fix it and provide PR or at all look for more modern Java Skype API.
As a short-term solution - to use account with old not email skype login (if it's possible).

**Comment by hleb-kastseika** [comment]
I suggest to work on this issue in scope of story https://github.com/last-khajiit/skype2gitter/projects/1#card-4358135, and as a temporary solution to use only old Skype accounts.
